import streamlit as st

def show():
    st.title("🎯 Smart Interview System")
    st.markdown("### AI-Powered Interview Platform with Intelligent Proctoring")
    st.markdown("---")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.info("🤖 AI Question Generation\n\nDomain-specific questions generated by Gemini AI")
    with col2:
        st.success("👁️ Intelligent Proctoring\n\nReal-time face, audio & tab monitoring")
    with col3:
        st.warning("📊 Smart Evaluation\n\nNLP-based answer scoring & detailed reports")

    st.markdown("---")
    st.markdown("### Get Started")
    st.write("Use the sidebar to navigate:")
    st.write("- **Start Interview** → For candidates")
    st.write("- **Recruiter Dashboard** → For recruiters to view results")